const STATIC_HOST=location.hostname.endsWith('github.io');
const API_BASE=location.protocol==='file:'?'http://localhost:5000/api':'/api';
setTimeout(()=>{if(document.getElementById('dash')&&current())syncUserSettings()},0);
async function continueWithGoogle(){try{const config=await fetch(`${API_BASE}/auth/config`).then(response=>response.json());if(!config.key)throw new Error('Supabase publishable key is not configured.');const client=window.supabase.createClient(config.url,config.key);const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}/login.html`}});if(error)throw error}catch(error){alert(error.message||'Google sign-in is unavailable.')}}
async function finishGoogleSignIn(){if(!window.supabase||!document.getElementById('loginForm'))return;const config=await fetch(`${API_BASE}/auth/config`).then(response=>response.json());if(!config.key)return;const client=window.supabase.createClient(config.url,config.key);const {data}=await client.auth.getSession();if(!data.session)return;const authUser=data.session.user;const user={name:authUser.user_metadata?.full_name||authUser.user_metadata?.name||authUser.email,email:authUser.email,role:authUser.user_metadata?.role||'trainee'};await fetch(`${API_BASE}/user/profile`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(user)});setCurrent(user);location.href='dashboard.html'}
const courses=[
['Full Stack Web Development','HTML, CSS, JavaScript, Node.js, REST APIs','Web','https://www.youtube.com/embed/nu_pCVPKzTk','Build a production-style learning portal','https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80'],
['Python Programming','Python fundamentals, OOP, files, APIs','Python','https://www.youtube.com/embed/rfscVS0vtbw','Build a CLI automation toolkit','https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=900&q=80'],
['Java Programming','Core Java, OOP, collections, exceptions','Java','https://www.youtube.com/embed/eIrMbAQSU34','Build a banking service','https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80'],
['React.js','Components, hooks, routing, state management','Frontend','https://www.youtube.com/embed/SqcY0GlETPk','Build a task management SPA','https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=900&q=80'],
['Node.js & Express','Servers, middleware, REST APIs, auth','Backend','https://www.youtube.com/embed/Oe421EPjeBE','Build an API for an e-commerce app','https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=80'],
['SQL & Database Engineering','SQL, joins, indexes, schema design','Database','https://www.youtube.com/embed/HXV3zeQKqGY','Design a reporting database','https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=900&q=80'],
['Git & GitHub','Branches, pull requests, workflows, collaboration','DevOps','https://www.youtube.com/embed/RGOj5yH7evk','Run a team Git workflow','https://images.unsplash.com/photo-1556075798-4825dfaaf498?auto=format&fit=crop&w=900&q=80'],
['Data Structures & Algorithms','Arrays, trees, graphs, complexity','CS','https://www.youtube.com/embed/8hly31xKli0','Implement a search and recommendation engine','https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=900&q=80'],
['Machine Learning with Python','Regression, classification, evaluation','AI/ML','https://www.youtube.com/embed/7eh4d6sabA0','Predict customer churn','https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=900&q=80'],
['Generative AI & Prompt Engineering','LLMs, prompts, RAG concepts, evaluation','AI','https://www.youtube.com/embed/hJP5GqnTrNo','Build an AI knowledge assistant','https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=80'],
['Cloud Fundamentals','Compute, storage, networking, deployment','Cloud','https://www.youtube.com/embed/M988_fsOSWo','Deploy a web application','https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=900&q=80'],
['Docker & Containers','Images, containers, Compose, registries','DevOps','https://www.youtube.com/embed/pg19Z8LL06w','Containerize a multi-service app','https://images.unsplash.com/photo-1605745341112-85968b19335b?auto=format&fit=crop&w=900&q=80'],
['Cybersecurity Foundations','OWASP, auth, secrets, secure coding','Security','https://www.youtube.com/embed/inWWhr5tnEA','Perform a secure-code review','https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=900&q=80'],
['TypeScript','Types, generics, interfaces, tooling','Frontend','https://www.youtube.com/embed/30LWjhZzg50','Migrate a JavaScript app to TypeScript','https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=900&q=80'],
['Angular','Components, services, forms, routing','Frontend','https://www.youtube.com/embed/3qBXWUpoPHo','Build an enterprise dashboard','https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80'],
['DevOps CI/CD','Pipelines, testing, deployment automation','DevOps','https://www.youtube.com/embed/1er2cjUq1UI','Create a CI/CD pipeline','https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80'],
['Software Testing','Unit, integration, API and UI testing','QA','https://www.youtube.com/embed/uFTFsKmkCc8','Build an automated test suite','https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80'],
['UI/UX for Developers','Accessibility, design systems, responsive UI','Design','https://www.youtube.com/embed/c9Wg6Cb_YlU','Redesign a SaaS workflow','https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=900&q=80'],
['System Design','Scalability, caching, queues, architecture','Architecture','https://www.youtube.com/embed/bUHFg8CZFws','Design a high-traffic platform','https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=80'],
['Mobile App Development','Cross-platform app architecture and APIs','Mobile','https://www.youtube.com/embed/VPvVD8t02U8','Build a mobile service app','https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=900&q=80']];
const defaultSettings={ai:true,live:true,certificates:true,notifications:true,reminders:true};
function users(){return JSON.parse(localStorage.getItem('cc_users')||'[]')}
function saveUsers(v){localStorage.setItem('cc_users',JSON.stringify(v))}
function seed(){if(!localStorage.getItem('cc_progress'))localStorage.setItem('cc_progress','{}');if(!localStorage.getItem('cc_trainer_courses'))localStorage.setItem('cc_trainer_courses',JSON.stringify([]));if(!localStorage.getItem('cc_settings'))localStorage.setItem('cc_settings',JSON.stringify({}))}
seed();
function current(){return JSON.parse(localStorage.getItem('cc_current')||'null')}
function setCurrent(u){localStorage.setItem('cc_current',JSON.stringify(u))}
function localAuth(mode,payload){
	const saved=users();
	if(mode==='register'){
		if(saved.some(user=>user.email===payload.email))throw new Error('An account with this email already exists.');
		const user={name:payload.name,email:payload.email,role:payload.role||'trainee',password:payload.password};
		saveUsers([...saved,user]);
		return user;
	}
	const user=saved.find(item=>item.email===payload.email&&item.password===payload.password);
	if(!user)throw new Error('Invalid email or password.');
	return user;
}
function userSettings(){const u=current();const data=JSON.parse(localStorage.getItem('cc_settings')||'{}');return {...defaultSettings,...(u?data[u.email]||{}:{})}}
async function syncUserSettings(){const u=current();if(!u)return userSettings();try{const response=await fetch(`${API_BASE}/user/settings?email=${encodeURIComponent(u.email)}`);if(!response.ok)throw new Error('Settings request failed');const settings={...defaultSettings,...await response.json()};const data=JSON.parse(localStorage.getItem('cc_settings')||'{}');data[u.email]=settings;localStorage.setItem('cc_settings',JSON.stringify(data));return settings}catch(error){return userSettings()}}
function saveUserSettings(settings){const u=current();if(!u)return;const saved={...defaultSettings,...settings};const data=JSON.parse(localStorage.getItem('cc_settings')||'{}');data[u.email]=saved;localStorage.setItem('cc_settings',JSON.stringify(data));fetch(`${API_BASE}/user/settings`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:u.email,settings:saved})}).catch(()=>{});}
function logout(){localStorage.removeItem('cc_current');location.href='index.html'}
function showAuth(mode='login'){const m=document.getElementById('authModal');if(!m)return;m.classList.remove('hidden');document.getElementById('authTitle').textContent=mode==='register'?'Create your account':'Welcome back';document.getElementById('authSubmit').textContent=mode==='register'?'Create account':'Login';document.getElementById('name').style.display=mode==='register'?'block':'none';document.getElementById('role').style.display=mode==='register'?'block':'none';document.getElementById('authForm').dataset.mode=mode;document.getElementById('authSwitch').innerHTML=mode==='register'?'Already have an account? <a href="#" onclick="showAuth(\'login\');return false">Sign in</a>':'New user? <a href="#" onclick="showAuth(\'register\');return false">Create account</a>'}
function hideAuth(){document.getElementById('authModal')?.classList.add('hidden')}
async function authSubmit(e){e.preventDefault();const f=e.target,mode=f.dataset.mode,email=document.getElementById('email').value.trim().toLowerCase(),password=document.getElementById('password').value;const payload={email,password};if(mode==='register'){payload.name=document.getElementById('name').value.trim();payload.role=document.getElementById('role').value}try{if(STATIC_HOST){setCurrent(localAuth(mode,payload));location.href='dashboard.html';return}const response=await fetch(`${API_BASE}/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.message||'Authentication failed');if(mode==='register'&&!result.session){alert(result.message);showAuth('login');return}setCurrent(result.user);location.href='dashboard.html'}catch(error){if(!STATIC_HOST){alert(error.message||'Unable to connect to the server.');return}alert(error.message||'Unable to create the account.');}}
document.getElementById('authForm')?.addEventListener('submit',authSubmit);
finishGoogleSignIn().catch(()=>{});
document.getElementById('loginNav')?.addEventListener('click',()=>showAuth('login'));
if(document.getElementById('coursePreview'))document.getElementById('coursePreview').innerHTML=courses.map((c,i)=>`<article class="glass card course-preview"><img class="course-image" src="${c[5]}" alt="${c[0]} course illustration" loading="lazy"><b>${i+1}. ${c[0]}</b><p>${c[1]}</p><span class="pill">${c[2]}</span></article>`).join('');
if(localStorage.getItem('openRegister')){localStorage.removeItem('openRegister');setTimeout(()=>showAuth('register'),100)}
if(document.getElementById('loginForm'))document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();const email=document.getElementById('email').value.trim().toLowerCase(),password=document.getElementById('password').value;try{if(STATIC_HOST){setCurrent(localAuth('login',{email,password}));location.href='dashboard.html';return}const response=await fetch(`${API_BASE}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const result=await response.json();if(!response.ok)throw new Error(result.message||'Invalid credentials');setCurrent(result.user);location.href='dashboard.html'}catch(error){document.getElementById('loginMsg').textContent=error.message||'Unable to connect to the server.';}});
function decorateCourseImages(){document.querySelectorAll('#dash .course').forEach((card,i)=>{if(card.querySelector('.course-image')||!courses[i]?.[5])return;const image=document.createElement('img');image.className='course-image';image.src=courses[i][5];image.alt=`${courses[i][0]} course illustration`;image.loading='lazy';card.prepend(image)})}
function progress(){return JSON.parse(localStorage.getItem('cc_progress')||'{}')}
function setProgress(p){localStorage.setItem('cc_progress',JSON.stringify(p))}
function enroll(i){const u=current();let p=progress();p[u.email]??={};p[u.email][i]??={enrolled:true,modules:0,project:false,certificate:false};setProgress(p);toast('Enrolled in '+courses[i][0]) ;renderTrainee()}
function completeModule(i){const u=current(),p=progress();p[u.email]??={};p[u.email][i]??={enrolled:true,modules:0,project:false,certificate:false};p[u.email][i].modules=Math.min(5,(p[u.email][i].modules||0)+1);setProgress(p);toast('Module completed');renderTrainee()}
function submitProject(i){const u=current(),p=progress();p[u.email][i].project=true;p[u.email][i].certificate=true;setProgress(p);toast('Project submitted. Certificate unlocked.');renderTrainee()}
function certificate(i){const u=current();const w=window.open('','_blank');w.document.write(`<html><body style="font-family:Arial;text-align:center;padding:80px"><h1>CAPACITY CONNECT</h1><h2>Certificate of Project Completion</h2><p>This certifies that</p><h1>${u.name}</h1><p>completed the real-time project for</p><h2>${courses[i][0]}</h2><p>Issued ${new Date().toLocaleDateString()}</p><hr><p>CAPACITY CONNECT Learning Platform</p><script>window.print()<\/script></body></html>`);w.document.close()}
function renderTrainee(){const u=current(),p=progress()[u.email]||{};document.getElementById('roleBadge').textContent='Trainee';document.getElementById('dash').innerHTML=`<div class="dash-head"><div><p class="eyebrow">TRAINEE WORKSPACE</p><h1>Welcome, <span>${u.name.split(' ')[0]}</span></h1><p class="muted" style="text-align:left">Enroll, learn, complete modules, solve real-time problem statements and earn certificates.</p></div><button class="btn" onclick="conference()">🎥 Join live conference</button></div><div class="statgrid"><div class="glass stat"><strong>${Object.keys(p).length}</strong>Enrolled</div><div class="glass stat"><strong>${Object.values(p).filter(x=>x.modules>=5).length}</strong>Modules done</div><div class="glass stat"><strong>${Object.values(p).filter(x=>x.project).length}</strong>Projects</div><div class="glass stat"><strong>${Object.values(p).filter(x=>x.certificate).length}</strong>Certificates</div></div><section class="glass section"><h3>Course catalog</h3><div class="coursegrid">${courses.map((c,i)=>{let x=p[i],pct=x?Math.round(((x.modules||0)/5)*80+(x.project?20:0)):0;return `<div class="course"><b>${i+1}. ${c[0]}</b><div class="meta">${c[1]} · ${c[2]}</div><div class="progress"><i style="width:${pct}%"></i></div><div class="row">${x?`<span class="pill">${pct}% complete</span><button class="btn small" onclick="completeModule(${i})">Complete module</button><button class="btn small ghost" onclick="problem(${i})">Problem statement</button>`:`<button class="btn small" onclick="enroll(${i})">Enroll</button>`}${x&&x.project?`<button class="btn small" onclick="certificate(${i})">Certificate</button>`:''}</div>${x?`<details><summary>🎬 YouTube lesson</summary><iframe class="video" src="${c[3]}" title="YouTube lesson" allowfullscreen></iframe><p><b>Real-time project:</b> ${c[4]}</p></details>`:''}</div>`}).join('')}</div></section><section class="glass section"><h3>🤖 AI Learning Assistant</h3><div id="chat" class="chat"><div class="bubble">Hi ${u.name}! Ask me for a study plan, module explanation, project hint or interview practice.</div></div><div class="row"><input id="aiInput" class="field" style="flex:1" placeholder="Ask your learning question..." onkeydown="if(event.key==='Enter')askAI()"><button class="btn" onclick="askAI()">Ask AI</button></div></section>`}
function problem(i){const answer=prompt(`Problem statement for ${courses[i][0]}:\n\nBuild a working ${courses[i][4]}.\n\nEnter a short description of your solution to submit.`);if(answer){submitProject(i)}}
function askAI(){const input=document.getElementById('aiInput'),chat=document.getElementById('chat');if(!input?.value.trim())return;const q=input.value.trim();chat.innerHTML+=`<div class="bubble me">${escapeHtml(q)}</div>`;let a='Break the task into small steps, implement one module at a time, test it, then document your result.';if(/project|problem/i.test(q))a='For a project, define requirements → data model → API/UI → tests → deployment. Keep a README and submit a working demo.';if(/python/i.test(q))a='For Python practice, start with functions and data structures, then build a small API or automation script and add tests.';chat.innerHTML+=`<div class="bubble">${a}</div>`;input.value='';chat.scrollTop=chat.scrollHeight}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function trainerCourses(){return JSON.parse(localStorage.getItem('cc_trainer_courses')||'[]')}
function renderTrainer(){const u=current(),p=progress(),all=users().filter(x=>x.role==='trainee');document.getElementById('roleBadge').textContent='Trainer';document.getElementById('dash').innerHTML=`<div class="dash-head"><div><p class="eyebrow">TRAINER WORKSPACE</p><h1>Trainer <span>Studio</span></h1><p class="muted" style="text-align:left">Publish courses, prepare notes, assign real-time work and monitor trainee progression.</p></div><button class="btn" onclick="conference()">🎥 Create conference room</button></div><div class="statgrid"><div class="glass stat"><strong>${trainerCourses().length}</strong>Published courses</div><div class="glass stat"><strong>${all.length}</strong>Trainees</div><div class="glass stat"><strong>${Object.values(p).reduce((a,x)=>a+Object.keys(x||{}).length,0)}</strong>Enrollments</div><div class="glass stat"><strong>${Object.values(p).reduce((a,x)=>a+Object.values(x||{}).filter(v=>v.project).length,0)}</strong>Projects submitted</div></div><section class="glass section"><h3>Publish a course</h3><form onsubmit="publishCourse(event)" class="row"><input class="field" id="tcTitle" placeholder="Course title" required><input class="field" id="tcDesc" placeholder="Description" required><input class="field" id="tcVideo" placeholder="YouTube embed URL (optional)"><button class="btn">Publish</button></form><div class="coursegrid" style="margin-top:16px">${trainerCourses().map(x=>`<div class="course"><b>${x.title}</b><p>${x.desc}</p><span class="pill">Trainer published</span></div>`).join('')}</div></section><section class="glass section"><h3>Notes & real-time assignments</h3><textarea id="assignment" class="field" rows="4" placeholder="Write a real-time assignment or problem statement..."></textarea><button class="btn" onclick="saveAssignment()">Publish assignment</button><p id="assignmentStatus" class="muted" style="text-align:left"></p></section><section class="glass section"><h3>Trainee progression</h3><table class="table"><tr><th>Trainee</th><th>Enrollments</th><th>Modules</th><th>Projects</th><th>Certificates</th></tr>${all.map(t=>{const x=Object.values(p[t.email]||{});return `<tr><td>${t.name}<br><span class="meta">${t.email}</span></td><td>${x.length}</td><td>${x.reduce((a,v)=>a+(v.modules||0),0)}</td><td>${x.filter(v=>v.project).length}</td><td>${x.filter(v=>v.certificate).length}</td></tr>`}).join('')}</table></section>`}
function publishCourse(e){e.preventDefault();const a=trainerCourses();a.push({title:tcTitle.value,desc:tcDesc.value,video:tcVideo.value});localStorage.setItem('cc_trainer_courses',JSON.stringify(a));renderTrainer();toast('Course published')}
function saveAssignment(){localStorage.setItem('cc_assignment',document.getElementById('assignment').value);document.getElementById('assignmentStatus').textContent='Assignment saved and visible to trainees.';toast('Assignment published')}
function renderAdmin(){const u=users(),p=progress(),trainers=u.filter(x=>x.role==='trainer'),trainees=u.filter(x=>x.role==='trainee');document.getElementById('roleBadge').textContent='Admin';document.getElementById('dash').innerHTML=`<div class="dash-head"><div><p class="eyebrow">ADMIN CONSOLE</p><h1>Platform <span>Dashboard</span></h1><p class="muted" style="text-align:left">Manage users, courses, content, certificates, live sessions and platform settings.</p></div><button class="btn" onclick="conference()">🎥 Open conference</button></div><div class="statgrid"><div class="glass stat"><strong>${u.length}</strong>Total users</div><div class="glass stat"><strong>${trainees.length}</strong>Trainees</div><div class="glass stat"><strong>${trainers.length}</strong>Trainers</div><div class="glass stat"><strong>${courses.length+trainerCourses().length}</strong>Courses</div></div><section class="glass section"><h3>Admin controls</h3><div class="grid" style="padding:0"><article class="card"><b>👥 User management</b><p>View registered users, roles and access. Promote/demote roles in a production database.</p><button class="btn small" onclick="userReport()">View users</button></article><article class="card"><b>📚 Content moderation</b><p>Review trainer courses, assignments, notes, videos and problem statements.</p></article><article class="card"><b>🏆 Certificates</b><p>Review completion records and certificate activity.</p></article><article class="card"><b>📊 Analytics</b><p>Monitor registrations, enrollments, module completion and project submissions.</p></article><article class="card"><b>🔐 Access & security</b><p>Manage roles, sessions, authentication policies and audit logs.</p></article><article class="card"><b>⚙️ Platform settings</b><p>Configure branding, notifications, live-room defaults, integrations and AI provider.</p></article></div></section><section class="glass section"><h3>Recent user activity</h3><table class="table"><tr><th>User</th><th>Role</th><th>Enrollments</th><th>Projects</th></tr>${u.map(x=>{const q=Object.values(p[x.email]||{});return `<tr><td>${x.name}<br>${x.email}</td><td><span class="pill">${x.role}</span></td><td>${q.length}</td><td>${q.filter(v=>v.project).length}</td></tr>`}).join('')}</table></section>`}
function userReport(){alert(users().map(x=>`${x.name} — ${x.email} — ${x.role}`).join('\n'))}
function openProfile(){const u=current();alert(`Profile\n\nName: ${u.name}\nEmail: ${u.email}\nRole: ${u.role}\n\nYou can update profile fields here in the production database.`)}
function openSettings(){const panel=document.getElementById('settingsModal'),content=document.getElementById('settingsContent');if(!panel||!content)return;const settings=userSettings();content.innerHTML=`<div class="toggle-row"><div><strong>AI assistant</strong><p class="muted">Use the learning assistant and chat support.</p></div><label class="switch"><input type="checkbox" ${settings.ai!==false?'checked':''} data-key="ai"><span class="slider"></span></label></div><div class="toggle-row"><div><strong>Live conference</strong><p class="muted">Open Jitsi rooms and virtual sessions.</p></div><label class="switch"><input type="checkbox" ${settings.live!==false?'checked':''} data-key="live"><span class="slider"></span></label></div><div class="toggle-row"><div><strong>Certificates</strong><p class="muted">Download project completion certificates.</p></div><label class="switch"><input type="checkbox" ${settings.certificates!==false?'checked':''} data-key="certificates"><span class="slider"></span></label></div><div class="toggle-row"><div><strong>Notifications</strong><p class="muted">Get course and assignment updates.</p></div><label class="switch"><input type="checkbox" ${settings.notifications!==false?'checked':''} data-key="notifications"><span class="slider"></span></label></div><div class="toggle-row"><div><strong>Progress reminders</strong><p class="muted">Show reminders to continue learning.</p></div><label class="switch"><input type="checkbox" ${settings.reminders!==false?'checked':''} data-key="reminders"><span class="slider"></span></label></div><button class="btn" onclick="closeSettings();toast('Settings saved');">Save settings</button>`;panel.classList.remove('hidden');panel.querySelectorAll('input[data-key]').forEach(input=>input.addEventListener('change',()=>{const next=userSettings();next[input.dataset.key]=input.checked;saveUserSettings(next);if(document.getElementById('dash')){const u=current();if(!u)location.href='login.html';else if(u.role==='admin')renderAdmin();else if(u.role==='trainer')renderTrainer();else renderTrainee();}}))}
function closeSettings(){document.getElementById('settingsModal')?.classList.add('hidden')}
function conference(){const settings=userSettings();if(settings.live===false){toast('Live conference is disabled in Settings.');return}const room='capacity-connect-'+Math.random().toString(36).slice(2,10);window.open('https://meet.jit.si/'+room,'_blank');toast('Live conference room opened')}
function toast(s){const t=document.getElementById('toast');if(!t)return;t.textContent=s;t.style.display='block';setTimeout(()=>t.style.display='none',2200)}
if(document.getElementById('dash')){const dash=document.getElementById('dash');new MutationObserver(decorateCourseImages).observe(dash,{childList:true,subtree:true});const u=current();if(!u)location.href='login.html';else if(u.role==='admin')renderAdmin();else if(u.role==='trainer')renderTrainer();else renderTrainee()}
